name: Build OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      version:
        description: 'OpenWrt version'
        required: true
        default: '24.10'
        type: string

env:
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
  REPO_BRANCH: openwrt-24.10
  BUILD_ROOT: ${{ github.workspace }}/openwrt
  DEPENDENCIES: ${{ github.workspace }}/dependencies-ubuntu.txt
  CONFIG_FILE: ${{ github.workspace }}/config/rt18000.config
  TZ: UTC

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install $(cat $DEPENDENCIES)
        sudo apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"

    - name: Maximize build disk space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: true
        remove-android: true
        remove-haskell: true
        remove-codeql: true
        remove-docker-images: true

    - name: Checkout
      uses: actions/checkout@main

    - name: Download the sources
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH

    - name: Copy config file
      run: cp -a $CONFIG_FILE $BUILD_ROOT/.config

    - name: Build the firmware image
      id: compile
      run: |
        cd $BUILD_ROOT && echo "$(($(nproc)+1)) thread compile"
        IGNORE_ERRORS=m make -j$(($(nproc)+1)) defconfig download clean world || IGNORE_ERRORS=m make -j1 defconfig download clean world V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Check space usage
      run: df -hT

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success'
      with:
        name: bin
        path: ${{ env.BUILD_ROOT }}/bin
